### PR TITLE
Configure NODE_PATH to load plugin from GitHub workspace

### LINKED ISSUE #16: Lighthouse Plugin doesn't work without hacks
I created a sample project with a Lighthouse Plugin for my blogpost: https://engineering.q42.nl/making-a-lighthouse-plugin-work-with-lighthouse-ci/.

I couldn't get it to work on GitHub Actions without adding the lines:

```
- run: npm install lighthouse
- run: mv node_modules/lighthouse-plugin-social-sharing
```

Otherwise it gave te error messages:
`Runtime error encountered: Cannot find module 'lighthouse'`
`Runtime error encountered: Unable to locate plugin: lighthouse-plugin-field-social-sharing`

My sample repo is: https://github.com/Q42/lighthouse-plugin-sample-project

### PR DESCRIPTION
**Pull request by connorjclark**
Fixes #16

This change supports plugins w/ no changes to a workspace config, other than running `npm/yarn install`. See my example repo: https://github.com/connorjclark/lighthouse-plugin-sample-project/blob/master/.github/workflows/main.yml

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -1,8 +1,21 @@
+// Append the node_modules of the github workspace and the node_modules of this action
+// to NODE_PATH. This supports lighthouse plugins - all the workspace needs to do it
```
Comment (exterkamp) [inline src/index.js]: I think this comment is enough, then explain more in detail in the docs.

```suggestion
// to NODE_PATH.
```

File: src/index.js [hunk 2]
```diff
@@ -1,8 +1,21 @@
...
+  `${process.env.GITHUB_WORKSPACE}/node_modules`,
+];
+process.env.NODE_PATH = nodePathParts.join(nodePathDelim);
+
 const core = require('@actions/core')
 const childProcess = require('child_process')
 const lhciCliPath = require.resolve('@lhci/cli/src/cli.js')
 const input = require('./input.js')
 
+
```
Comment (exterkamp) [inline src/index.js]:
```suggestion
```
